### ISSUE TITLE
Shop 등록 API 스펙 변경

### ISSUE THREAD

**Issue by sssukho** [f-lab-edu/beautify-project#10]
샵 등록시 필요한 이미지 업로드 기능은 s3 `presignedurl` 을 활용하여 클라이언트에서 직접 S3 로 파일 업로드를 하는 방향으로 API 스펙 변경

### TODO

- [x] API 문서 수정
- [x] Shop 등록 컨트롤러 수정
- [x] Shop 등록 서비스 수정
