### ISSUE TITLE
preSignedUrl 을 이용한 이미지 파일 URL 저장/조회 기능

### ISSUE THREAD

**Issue by sssukho** [f-lab-edu/beautify-project#12]
### 이미지 업로드시 동작 흐름
1. (Client) Shop 의 이미지 업로드가 필요할 경우 api 서버로 `preSignedUrl` 을 요청한다.
2. (Server) Object Storage 로 `preSignedUrl` 을 PUT 권한으로 요청한다.
3. (Server) Client 로 `preSignedUrl` 을 응답으로 내려준다.
4. (Client) `preSignedUrl` 로 이미지 바이너리 저장을 요청한다.
5. (Client) `preSignedUrl` 을 포함하여 Shop 등록에 필요한 데이터들과 함께 api 서버로 전송한다.
6. (Server) 수신받은 preSignedurl 을 저장한다. 이 때, thumbnail 은 요청온 imageUrl 리스트에서 가장 첫 번째 요소로 한다.

### 이미지 조회시 동작 흐름 - Shop 리스트 조회시
1. (Client) Shop 의 리스트를 조회 요청한다.
2. (Server) Shop들의 데이터들과 thumbnail 이미지 url 을 포함하여 응답한다.
3. (Client) 응답받은 thumbnail 이미지 url 로 리스트 조회시 화면에 뿌린다.

### 이미지 조회시 동작 흐름 - Shop 상세 조회시
1. (Client) Shop 의 상세 조회를 요청한다.
2. (Server) Shop의 데이터들과 모든 이미지 url 을 포함하여 응답한다.
3. (Client) 응답받은 이미지 url 들로 상세 조회시 화면에 뿌린다.

### TODO
- [x] API 스펙 작성 및 수정
- [x] s3 client 사용 방법 리서치
- [x] preSignedUrl 을 응답하는 API 구현
- [x] controller 테스트 코드 작성
- [x] service 테스트 코드 작성
