### ISSUE TITLE
Shop 좋아요

### ISSUE THREAD

**Issue by sssukho** [f-lab-edu/beautify-project#18]
### TODO
- [x] Shop 좋아요/취소 API 설계
- [x] Shop 좋아요 API 구현
- [x] Shop 좋아요 취소 API 구현
