### ISSUE TITLE
DB 변경

### ISSUE THREAD

**Issue by sssukho** [f-lab-edu/beautify-project#21]
![스크린샷 2024-12-11 오전 3 57 00](https://github.com/user-attachments/assets/179a8874-eaa8-4e9e-ab73-3e3553bb0dea)

### TODO
- [ ] Postgresql, MySQL 차이점 정리
- [x] docker-compose 파일 수정
- [x] datasource 설정 수정
