### ISSUE TITLE
설정 파일 암호화

### ISSUE THREAD

**Issue by sssukho** [f-lab-edu/beautify-project#24]
### TODO
- [x] 암호화 방식 및 키 관리 방식 선정
- [x] 암호화 필요 항목 선정
- [x] 필요 항목 암호화
