### ISSUE TITLE
예약 정보 생성

### ISSUE THREAD

**Issue by sssukho** [f-lab-edu/beautify-project#31]
### TODO
- [x] 예약 엔티티 정의 => 어떤 데이터가 필요한지?
- [x] 예약 등록 컨트롤러
- [x] 예약 등록 서비스
- [x] 예약 등록 레파지토리
