### ISSUE TITLE
Service 프로덕션/테스트 코드 리펙토링

### ISSUE THREAD

**Issue by sssukho** [f-lab-edu/beautify-project#9]
### 요구사항
- [Service 코드 및 테스트 코드 작성 issue](https://github.com/f-lab-edu/beautify-project/issues/7) 에서 피드백 받은 내용 반영

### TODO
- [x] Shop 등록 컨트롤러 테스트 코드 수정
- [x] Shop 등록 서비스 테스트 코드 수정
- [x] Shop 리스트 조회 컨트롤러 테스트 코드 수정
- [x] Shop 리스트 조회 서비스 테스트 코드 수정
- [x] Review 조회 컨트롤러 테스트 코드 수정
- [x] Review 리스트 조회 컨트롤러 테스트 코드 수정
- [x] Review 조회 서비스 테스트 코드 수정
- [x] Review 리스트 조회 테스트 코드 수정
- [x] 불필요 코드 삭제 (StorageService, 주석 등등)
- [x] TestFixture 사용하지 않는 방향으로 수정
- [ ] ~~Exception 이랑 ErrorCode 통합하는 방향으로 수정~~
- [x] 테스트 코드에서 `@Transactional` 사용하지 않는 방향으로 수정
